# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build PIM .NET and publish

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build-project:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies For Lincoln API
      run: dotnet restore LincolnAPI

    - name: Build Lincoln API
      run: dotnet build LincolnAPI --no-restore

    - name: Test Lincoln API
      run: dotnet test APITest --no-build --verbosity normal

    - name: Restore dependencies For BeamerBlazor
      run: dotnet restore BeamerBlazor

    - name: Build BeamerBlazor
      run: dotnet build BeamerBlazor --no-restore

  build-container-LincolnAPI:
    needs: build-project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file LincolnAPI/Dockerfile --tag kilali/pim:$(date +%s) 
